// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int /Users/admin/work/go/voyage/internal/pkg/code"; DO NOT EDIT.

package code

// init register errors codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(ErrUserNotFound, 200, "User not found.")
	register(ErrUserAlreadyExist, 200, "User already exist.")
	register(ErrFailedAuthentication, 200, "username or password error")
	register(ErrCreateBaseMenu, 200, "创建菜单失败")
	register(ErrSuccess, 200, "OK.")
	register(ErrUnknown, 500, "Internal server error.")
	register(ErrBind, 400, "Error occurred while binding the request body to the struct.")
	register(ErrValidation, 400, "Validation failed.")
	register(ErrTokenInvalid, 401, "Token invalid.")
	register(ErrTokenExpired, 200, "Token Expired.")
	register(ErrPageNotFound, 404, "Page not found.")
	register(ErrGetCaptcha, 200, "图形验证码获取失败")
	register(ErrInvalidCaptcha, 200, "无效的图形验证码")
	register(ErrInsufficientPermissions, 200, "Insufficient permissions")
	register(ErrDatabase, 500, "Database error.")
	register(ErrEncrypt, 401, "Error occurred while encrypting the sysuser password.")
	register(ErrSignatureInvalid, 401, "Signature is invalid.")
	register(ErrExpired, 401, "Token expired.")
	register(ErrInvalidAuthHeader, 401, "Invalid authorization header.")
	register(ErrMissingHeader, 401, "The `Authorization` header was empty.")
	register(ErrPasswordIncorrect, 401, "Password was incorrect.")
	register(ErrPermissionDenied, 403, "Permission denied.")
	register(ErrEncodingFailed, 500, "Encoding failed due to an error with the data.")
	register(ErrDecodingFailed, 500, "Decoding failed due to an error with the data.")
	register(ErrInvalidJSON, 500, "Data is not valid JSON.")
	register(ErrEncodingJSON, 500, "JSON data could not be encoded.")
	register(ErrDecodingJSON, 500, "JSON data could not be decoded.")
	register(ErrInvalidYaml, 500, "Data is not valid Yaml.")
	register(ErrEncodingYaml, 500, "Yaml data could not be encoded.")
	register(ErrDecodingYaml, 500, "Yaml data could not be decoded.")
}
