// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int /Users/admin/work/go/go-project/internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(Success, 200, "OK.")
	register(ErrUnknown, 200, "内部服务错误")
	register(ErrBind, 200, "请求参数绑定错误")
	register(ErrValidation, 200, "参数验证错误")
	register(ErrTokenInvalid, 200, "无效的token")
	register(ErrDatabase, 200, "Database error.")
	register(ErrEncrypt, 200, "Error occurred while encrypting the user password.")
	register(ErrSignatureInvalid, 200, "Signature is invalid.")
	register(ErrExpired, 200, "Token expired.")
	register(ErrInvalidAuthHeader, 200, "Invalid authorization header.")
	register(ErrMissingHeader, 200, "The `Authorization` header was empty.")
	register(ErrPasswordIncorrect, 200, "Password was incorrect.")
	register(ErrPermissionDenied, 200, "Permission denied.")
	register(ErrEncodingFailed, 200, "Encoding failed due to an error with the data.")
	register(ErrDecodingFailed, 200, "Decoding failed due to an error with the data.")
	register(ErrInvalidJSON, 200, "Data is not valid JSON.")
	register(ErrEncodingJSON, 200, "JSON data could not be encoded.")
	register(ErrDecodingJSON, 200, "JSON data could not be decoded.")
	register(ErrInvalidYaml, 200, "Data is not valid Yaml.")
	register(ErrEncodingYaml, 200, "Yaml data could not be encoded.")
	register(ErrDecodingYaml, 200, "Yaml data could not be decoded.")
}
