
version: "3.8"

services:

  #============= redis ================
  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass
      - ${REDIS_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./configs/dev/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.tmp/redis/data:/data

  #============= mysql ================
  mysql:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
      - ./configs/dev/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
